apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      env:
        # Depuis le ConfigMap
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: mon-config
              key: APP_ENV
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: mon-config
              key: APP_NAME
        # Depuis le Secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mon-secret
              key: DB_PASSWORD
